name: s_rocks_music_assignment
description: Assignment project for S-Rocks Music

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  provider: ^6.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter:
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

  uses-material-design: true
  
  assets:
    - assets/
    - assets/graphics/
    - assets/images/
    - assets/icons/